# Generated by Django 4.1.5 on 2023-01-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Daytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=75)),
                ('lat', models.FloatField(default=None, null=True)),
                ('long', models.FloatField(default=None, null=True)),
                ('city', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('public', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mad_api.category')),
                ('daytime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mad_api.daytime')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=200)),
                ('edited', models.DateField(default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.event')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_api.user')),
            ],
        ),
    ]
