# Generated by Django 4.1.3 on 2023-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='public_id',
            field=models.CharField(default='testingtesgingtesting', max_length=75),
            preserve_default=False,
        ),
    ]
