# Generated by Django 4.1.5 on 2023-01-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_api', '0002_daytime_alter_event_daytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.DateField(default=None, null=True),
        ),
    ]
